[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jett Chen", email = "jettchen12345@gmail.com" }
]
dependencies = [
    "modal>=0.62.87",
    "geoclip>=1.2.0",
    "pandas>=2.2.2",
    "torch>=2.2.2",
    "torchvision>=0.17.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipython>=8.23.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/ml"]

[[tool.rye.sources]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
